{{- if and (not .Values.existingSecret) .Values.secretEnv.DEEPSEEK_API_KEY }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ether-music.secretName" . }}
  labels:
    {{- include "ether-music.labels" . | nindent 4 }}
type: Opaque
stringData:
  DEEPSEEK_API_KEY: {{ .Values.secretEnv.DEEPSEEK_API_KEY | quote }}
{{- end }}
